AWSTemplateFormatVersion: 2010-09-09
Description: Create ECR

Parameters:
  RepositoryName:
    Description: Repository name
    Type: String
Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName